#
# Line Follow Test Makefile
#
# this file counts on arduino-mk being installed - see
#    https://github.com/sudar/Arduino-Makefile
#

export ARDUINO_DIR=/usr/share/arduino
export ARDMK_DIR=/usr/share/arduino
export AVR_TOOLS_DIR=/usr

ARCHITECTURE  = avr
BOARD_TAG     = uno

MONITOR_PORT  = /dev/ttyACM0

USER_LIB_PATH = ../..

include $(ARDMK_DIR)/Arduino.mk
